service: skrf-platform
provider:
  name: aws
  runtime: nodejs14.x
  stage: server
  region: ap-south-1
  memorySize: 128
functions:
  app:
    handler: lambda.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true